site_name: Documentations I.FA-P3B

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

theme:
  name: material
  features:
    - content.code.copy

  palette:
  
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: slate
        primary: amber
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
  
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: deep purple
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

  
#theme:
#  name: bootstrap386

#theme:
#  name: simple-blog

#theme: 
#  name: windmill-dark